name: Java to Kotlin

on:
  push:
    branches:
      - main
      - d
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  migrate:
    name: Migrate Java toKotlin Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
          
      - name: Kotlin Migration Monitor
        uses: JuriKiin/kotlin-migration-monitor@2024.4.25
        with:
          directory: './app'
          github-token: ${{ secrets.GITHUB_TOKEN }}