name: Migration CI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  #pages: write
  #id-token: write

jobs:
  migrate:
    name: Migrate
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Action runs: using: node20 as defined in
          # https://github.com/cypress-io/github-action/blob/master/action.yml
          # Node.js minor version is aligned to
          # https://github.com/actions/runner/blob/main/src/Misc/externals.sh
          node-version: 20.19.0
        #with:
          #node-version: '20'
        
      #- name: Install Node.js
      #  run: npm install

      - name: Calculate Migration Progress
        uses: JuriKiin/kotlin-migration-monitor@2024.4.25
        with:
          #directory: './path/to/files'
          directory: './app/src/main/java/com/rk/xededitor'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
